mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.khgears.quote.pojo
spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          password: agni616236
          url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=Quote
          username: agni
        sap:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          password: sap0.123
          url: jdbc:sqlserver://10.1.1.27:1433;DatabaseName=kh2015
          username: sa
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    servlet:
      content-type: text/html


